from tools.recommend_doctors import recommend_doctors
from tools.Appointment import book_appointment
from tools.Available_slots import get_available_slots
from tools.Check_Appointment import Check_patient_Appointment
from tools.validatedate import validate_appointment_date
from tools.cancelappointmetn import cancel_appointment
from tools.hospitalinfo  import retrieve_hospital_info
tools=[recommend_doctors,get_available_slots,book_appointment,Check_patient_Appointment,validate_appointment_date,cancel_appointment,retrieve_hospital_info]