from tools.Book_Appointment import book_appointment
from tools.cancel_appointment import cancel_appointment
from tools.check_appointment import check_appointments
from tools.check_available_slots import check_available_slots
from tools.get_doctor import search_doctor

tools=[search_doctor,check_available_slots,check_appointments,cancel_appointment,book_appointment]